### ISSUE TITLE
simply doesn't work

### ISSUE THREAD

**Issue by cydrobolt** [ehzhang/sense-js#4]
What phones/browsers does this work on? On my Moto G with Chrome 39, none of the things work.

**Comment by ehzhang** [comment]
Hi Cydrobolt!

This has been tested with numerous Android phones, among them the Droid 2 Global and the Moto X, as well as iPhone 6, 5, 5s, and 4, running Safari and Chrome.

Have you tried playing around with the demos? Navigating to http://sense-js.jit.su/orientation or http://sense-js.jit.su/flick are easy ways to test that the library works on your device.

Otherwise, let me know how you're using it!

**Comment by ehzhang** [comment]
Closing this issue due to age. Feel free to reopen if you are still facing these issues.

**Comment by cydrobolt** [comment]
@ehzhang yeah, the issue is still occurring, but I'm guessing it won't work on my phone.
